// vuln.hpp

#pragma once

#include "port.h"
#include "finding.h"
#include "core/knowledge_base.hpp"

#include <string>
#include <optional>
#include <vector>

namespace vuln {
    struct Version {
        std::string raw;
        std::vector<int> components;
    };

    struct VersionRange {
        std::string minimum;
        std::string maximum;
    };

    class VersionMatcher {
    public:
        static Version parse(const std::string& raw);
        static int compare(const Version& left, const Version& right);
        static bool in_range(const std::string& version, const VersionRange& range);
    };

    struct VerificationResult {
        bool vulnerable = false;
        std::string cve;
        std::string severity;
        std::string title;
        std::string description;
        std::string evidence;
        core::Evidence evidence_data;
        std::vector<std::string> references;
        std::string remediation;
        double cvss = -1.0;
        std::string cvss_vector;
        double confidence = 0.0;
        std::string verification = "UNKNOWN";
    };

    struct CveMatch {
        std::string cve_id;
        std::string product;
        std::string version;
        std::string severity;
        std::string description;
        double cvss = -1.0;
        std::string cvss_vector;
        std::string remediation;
        std::vector<std::string> references;
    };

    // Case-insensitive product match; returns comma-separated CVE IDs whose
    // (product, version_min, version_max) window includes `version`. Empty
    // string when nothing matches. Used from ZTL plugins.
    std::string lookup(const std::string& product, const std::string& version);

    std::optional<CveMatch> match(const std::string& cve_id,
                                  const std::string& product,
                                  const std::string& version);

    VerificationResult verify_version(const std::string& cve_id,
                                      const std::string& product,
                                      const std::string& version);

    void load_database(const std::string& path);

    // Load distro-backport info (generated by tools/cve_sync.py). Optional —
    // if the file is missing, check_port() still runs but every match stays
    // VERSION_MATCH regardless of Ubuntu/Debian package version.
    void load_distro_fixes(const std::string& path);

    std::vector<core::Finding> check_port(const core::Port& port);

    std::vector<core::Finding> run_native_checks(
        const core::Port& port,
        const std::string& target_ip,
        core::KnowledgeBase& kb
    );
}
